brewhouse/urls.py
from django.conf.urls import patterns, url, include
from tastypie.api import Api

import api


v1_api = Api(api_name='v1')
v1_api.register(api.TapResource())
v1_api.register(api.BeerResource())
v1_api.register(api.UpcomingResource())

urlpatterns = patterns('brewhouse.views',
    url(r'^$', 'display', name='brewhouse-display'),

    url(r'^history/$', 'history', name='brewhouse-history'),

    url(r'^beer/new/$', 'beer_new', name='beer-new'),
    url(r'^beer/(?P<id>\d+)/$', 'beer_show', name='beer-show'),
    url(r'^beer/(?P<beer_id>\d+)/gone/$', 'beer_gone'),

    url(r'^beer/(?P<beer_id>\d+)/reserve/$', 'new_reservation'),

    url(r'^event/(?P<event_id>\d+)/done/$', 'event_complete', name='event-complete'),

    url(r'^reservations/$', 'list_reservations'),
    url(r'^reservations/(?P<reservation_id>\d+)/delete/$', 'delete_reservation'),

    # API shiz
    url(r'^api/', include(v1_api.urls)),
)

home/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'home.views.home', name='home'),
    # url(r'^home/', include('home.foo.urls')),
    url(r'^brewhouse/', include('brewhouse.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^weight/', include('weight.urls')),
    
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

brewhouse/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.dispatch import receiver

from django.core.mail import send_mail
from django.template.loader import render_to_string


class Beer(models.Model):
    """
    A beer. What else are you expecting?

    Editable from main site
    """

    name        = models.CharField(max_length=100)
    style       = models.CharField(max_length=100, blank=True)
    recipe_url  = models.CharField(max_length=1024, blank=True)
    unreservable = models.BooleanField(default=False)

    class Meta:
        ordering = ['-id']

    def __unicode__(self):
        name = self.name
        brew_date = self.brew_date()

        if brew_date:
            name += " ({0})".format(brew_date)

        return name

    def current_state(self):
        state = None
        last_event = None
        now = datetime.datetime.now().date()

        for event in self.event_set.order_by('date'):
            if not last_event:
                last_event = event

            if event.completed and event.date >= last_event.date:
                # In case of a date tie, go with the higher ID number
                if event.date != last_event.date or event.id > last_event.id:
                    last_event = event
                    state = event.event_type

        return state

    def is_ready(self):
        ready = False

        for event in self.event_set.all():
            if event.event_type == 0 and not event.is_future():
                ready = True
                break

        return ready

    def is_started(self):
        started = False

        for event in self.event_set.all():
            if event.event_type == 1 and not event.is_future():
                started = True
                break

        return started

    def brew_date(self):
        brewed = None

        for event in self.event_set.all():
            if event.event_type == 1:
                brewed = event.date
                break

        return brewed

    def is_gone(self):
        gone = False

        for event in self.event_set.all():
            if event.event_type == 6:
                gone = True
                break

        return gone

    def is_reservable(self):
        # Assumes all reservations are for 1/2 gallon
        # and that we only release 3 gallons of a particular beer
        return not self.is_gone() and self.reservation_set.count() < 3 and not self.unreservable


class Event(models.Model):
    """
    Beer event (brewed, fermentation, etc.)

    Editable via main site
    """

    TYPES = (
        (0, 'Ready'),
        (1, 'Brewed'),
        (2, 'Primary Fermentation'),
        (3, 'Secondary Fermentation'),
        (4, 'Kegged'),
        (5, 'Bottled'),
        (6, 'Gone'),
        (7, 'Brewing'),
    )

    beer        = models.ForeignKey(Beer)
    fermenter   = models.ForeignKey('Fermenter', default=None, null=True, blank=True)
    event_type  = models.IntegerField(choices=TYPES)
    date        = models.DateField()
    completed   = models.BooleanField()

    class Meta:
        unique_together = ('beer', 'event_type')
        ordering = ['-beer', '-date', '-id']

    def __unicode__(self):
        return '%s - %s @ %s' % (self.beer, self.resolve_etype(), self.date)

    def resolve_etype(self):
        description = None

        for etype, desc in self.TYPES:
            if etype == self.event_type:
                description = desc

        return description

    def is_future(self):
        return self.date > datetime.datetime.now().date()


class Tap(models.Model):
    """
    Kegerator tap

    Must be edited via admin site
    """

    number  = models.IntegerField(primary_key=True)
    beer    = models.ForeignKey(Beer, null=True, blank=True)

    def __unicode__(self):
        return 'Tap #' + str(self.number)


class Fermenter(models.Model):
    """
    Fermentation vessel

    Must be edited via admin site
    """

    description = models.CharField(max_length=100)

    def __unicode__(self):
        return self.description


class Reservation(models.Model):
    """
    Reservation of a growler of beer for a user
    """

    beer = models.ForeignKey(Beer)
    user = models.ForeignKey(User)
    approved = models.BooleanField(default=False)
    fulfilled = models.BooleanField(default=False)

    def __unicode__(self):
        return unicode(self.beer) + " for " + self.user.username


# Signals - probably should be in a separate file but that feels like a waste
@receiver(pre_save, sender=Reservation)
def notify_reservation_user(sender, instance, **kwargs):
    # If the user has no email address, skip this
    try:
        original = Reservation.objects.get(pk=instance.id)
    except:
        original = None

    if original and instance.user.email:
        if not original.approved and instance.approved:
            msg = render_to_string('brewhouse/email/reservation_approved.html', {'reservation': instance})
            send_mail('Your beer reservation has been approved!', msg, 'home@nickpegg.com', [instance.user.email], fail_silently=True)
        if not original.fulfilled and instance.fulfilled:
            msg = render_to_string('brewhouse/email/reservation_fulfilled.html', {'reservation': instance})
            send_mail('Your beer reservation has been fulfilled!', msg, 'home@nickpegg.com', [instance.user.email], fail_silently=True)

brewhouse/forms.py
import datetime

from django import forms

from models import Beer, Event


class BeerForm(forms.Form):
    class Meta:
        model = Beer

class EventForm(forms.Form):
    class Meta:
        model = Event


class AddBeerForm(forms.Form):
    EVENT_TYPES = (
        (0, 'Ready'),
        (1, 'Brewed'),
        (2, 'Primary Fermentation'),
        (3, 'Secondary Fermentation'),
        (4, 'Kegged'),
        (5, 'Bottled'),
        (6, 'Ready'),
    )

    name        = forms.CharField(max_length=100)
    style       = forms.CharField(max_length=100, required=False)
    recipe_url  = forms.CharField(max_length=1024, required=False)

    brew_date   = forms.DateField(initial=datetime.datetime.now().date())

brewhouse/views.py
import datetime

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.contrib import messages

import util
from models import Beer, Event, Tap, Reservation
from forms import AddBeerForm
from tasks import tweet_event


def display(request):
    taps = Tap.objects.all().order_by('number')

    # Gather up the upcoming-but-not-ready beers
    beers = []
    for beer in util.not_done_beers():
        try:
            ready = beer.event_set.get(event_type=0).date
        except:
            ready = 'Unknown'

        try:
            brewed_on = beer.event_set.get(event_type=1).date
        except:
            brewed_on = 'Unknown'

        beers.append((beer, util.resolve_event_type(beer.current_state()), brewed_on, ready))

    # Gather up 10 beers and their brewed/ready events
    history = []
    for brewed_event in Event.objects.filter(event_type=1).order_by('-date')[:10]:
        beer = brewed_event.beer
        try:
            ready_event = beer.event_set.get(event_type=0)
        except:
            ready_event = None

        history.append((beer, brewed_event, ready_event))

    user_can_request = request.user.has_perm('brewhouse.add_reservation')

    return render(request, 'brewhouse/index.html', locals())


def history(request):
    # Gather up beers and their brewed/ready events
    history = []
    for brewed_event in Event.objects.filter(event_type=1).order_by('-date'):
        beer = brewed_event.beer
        try:
            ready_event = beer.event_set.get(event_type=0)
        except:
            ready_event = None

        history.append((beer, brewed_event, ready_event))

    return render(request, 'brewhouse/history.html', locals())


def beer_show(request, id):
    today = datetime.datetime.now().date()

    beer = get_object_or_404(Beer, pk=id)
    events = beer.event_set.filter(completed=True).filter(date__lte=today).order_by('date')
    future_events = beer.event_set.filter(completed=False).order_by('date')

    can_reserve = beer.is_reservable() and request.user.has_perm('brewhouse.add_reservation')
    beer_gone = beer.current_state() == 6

    return render(request, 'brewhouse/view_beer.html', locals())


@login_required
def beer_new(request):
    if not request.user.is_superuser:
        return redirect('brewhouse-display')

    if request.method == 'POST':
        form = AddBeerForm(request.POST)
        if form.is_valid():
            b = Beer()
            b.name = form.cleaned_data['name']
            b.style = form.cleaned_data['style']
            b.recipe_url = form.cleaned_data['recipe_url']
            b.save()

            # Create some basic events based on the brewed-on date
            # tuple is of (event_type, days_since_brew_date)
            brew_date = form.cleaned_data['brew_date']

            events = (
                (7, 0),     # brewing
                (1, 0),     # brewed
                (2, 0),     # primary fermentation
                (3, 7),     # secondary fermentation
                (4, 21),    # kegged
                (0, 28),    # ready!
            )

            for etype, num_days in events:
                event = Event()
                event.beer = b
                event.event_type = etype
                event.date = brew_date + datetime.timedelta(days=num_days)
                event.save()

            return redirect('beer-show', b.id)
        else:
            pass    # TODO set an error
    else:
        form = AddBeerForm()

    return render(request, 'brewhouse/new_beer.html', locals())


@user_passes_test(lambda u: u.is_staff)
def beer_gone(request, beer_id):
    beer = get_object_or_404(Beer, pk=beer_id)

    if beer.current_state() == 6:
        messages.error(request, "This beer is already marked as 'gone'!")
        return redirect('beer-show', beer.id)

    # Create a new event marking this beer as gone
    event = Event()
    event.beer = beer
    event.date = datetime.datetime.now().date()
    event.event_type = 6    # Hard-coding this is kind of gross...
    event.completed = True
    event.save()

    tweet_event.delay(event)

    return redirect('beer-show', beer.id)


@login_required
def event_complete(request, event_id):
    if not request.user.is_superuser:
        return redirect('brewhouse-display')

    event = get_object_or_404(Event, pk=event_id)
    event.completed = True
    event.date = datetime.datetime.now().date()
    event.save()

    tweet_event.delay(event)

    return redirect('beer-show', event.beer.id)


@login_required
def new_reservation(request, beer_id):
    beer = get_object_or_404(Beer, pk=beer_id)

    if not request.user.has_perm('brewhouse.add_reservation'):
        messages.warning(request, "You're not allowed to reserve beer.")
        return redirect('beer-show', beer_id)

    if not beer.is_reservable():
        messages.warning(request, "That beer is not reservable!")
        return redirect('beer-show', beer_id)

    if Reservation.objects.filter(user=request.user, beer=beer):
        # User has already reserved this beer!
        messages.error(request, "You've already reserved a growler of this beer!")
        return redirect('beer-show', beer_id)

    if request.method == "POST" and request.POST.get('doit'):
        r = Reservation()
        r.beer = beer
        r.user = request.user
        r.save()

        messages.success(request, "Your beer reservation request has been made and is pending approval.")
        return redirect('beer-show', beer_id)

    return render(request, 'brewhouse/new_reservation.html', locals())


@login_required
def list_reservations(request):
    if not request.user.has_perm('brewhouse.add_reservation'):
        return redirect('brewhouse-display')

    reservations = request.user.reservation_set.all()
    return render(request, 'brewhouse/reservations.html', locals())


@login_required
def delete_reservation(request, reservation_id):
    reservation = get_object_or_404(Reservation, pk=reservation_id)

    if request.user != reservation.user and not request.user.is_staff:
        messages.warning(request, "You cannot delete that reservation!")
    else:
        reservation.delete()
        messages.success(request, "Reservation removed")

    return redirect('brewhouse.views.list_reservations')

brewhouse/templates/brewhouse/history.html
{% extends "base.html" %}

{% block title %}Brewhouse History{% endblock %}

{% block content %}
<ul class="breadcrumb">
    <li><a href="/">Nick's Apartment</a> <span class="divider">/</span></li>
    <li><a href="{% url 'brewhouse-display' %}">Brewhouse</a> <span class="divider">/</span></li>
    <li class="active">History</li>
</ul>

<h2>Brewhouse History</h2>

<table class="table">
    <thead>
        <tr>
            <th>Beer</th>
            <th>Brewed on</th>
            <th>Ready on</th>
        </tr>
    </thead>
    {% for beer, brewed, ready in history %}
    <tr>
        <td><a href="{% url 'beer-show' beer.id %}">{{ beer.name }}</a></td>
        <td>{{ brewed.date }}</td>
        <td>{{ ready.date|default:"Unknown" }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

brewhouse/templates/brewhouse/index.html
{% extends "base.html" %}

{% block title %}Brewhouse{% endblock %}

{% block content %}
<ul class="breadcrumb">
    <li><a href="/">Nick's Apartment</a> <span class="divider">/</span></li>
    <li class="active">Brewhouse</li>
</ul>

{% if user_can_request or user.is_staff %}
<h2>Links</h2>
<ul class="nav nav-pills nav-stacked">
    {% if user_can_request %}
        <li><a href="{% url 'brewhouse.views.list_reservations' %}">Your beer reservations</a></li>
    {% endif %}
    {% if user.is_staff %}
        <li><a href="{% url 'beer-new' %}">Add a beer</a></li>
    {% endif %}
</ul>
{% endif %}


<div class="row">
<div class="span6">
<h2>What's on Tap</h2>
<table class="table">
    <thead>
        <tr>
            <th>Tap</th>
            <th>Beer</th>
            <th>Beer Style</th>
            <th>Brewed On</th>
        </tr>
    </thead>
    {% for tap in taps %}
    <tr>
        <td>{{ tap.number }}</td>
        <td>
            {% if tap.beer %}
            <a href="{% url 'beer-show' tap.beer.id %}">{{ tap.beer.name }}</a>
            {% else %}
            None
            {% endif %}
        </td>
        <td>{{ tap.beer.style|default:"Unknown" }}</td>
        <td>{{ tap.beer.brew_date|default:"Unknown" }}</td>
    </tr>
    {% endfor %}
</table>
</div>
<div class="span6">
<h2>What's Coming Up</h2>
<table class="table">
    <thead>
        <tr>
            <th>Beer</th>
            <th>Current State</th>
            <th>Estimated Finish</th>
        </tr>
    </thead>
    {% for beer, state, brewed, ready in beers %}
    <tr>
        <td><a href="{% url 'beer-show' beer.id %}">{{ beer.name }}</a></td>
        <td>{{ state|default:"Unknown" }}</td>
        <td>{{ ready }}</td>
    </tr>
    {% endfor %}
</table>
</div>
</div>

<h2>Last 10 Beers</h2>

<ul class="nav nav-pills">
    <li><a href="{% url 'brewhouse-history' %}">View Full History</a></li>
</ul>


<table class="table">
    <thead>
        <tr>
            <th>Beer</th>
            <th>Brewed on</th>
            <th>Ready on</th>
        </tr>
    </thead>
    {% for beer, brewed, ready in history %}
    <tr>
        <td><a href="{% url 'beer-show' beer.id %}">{{ beer.name }}</a></td>
        <td>{{ brewed.date }}</td>
        <td>{{ ready.date|default:"Unknown" }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

brewhouse/templates/brewhouse/new_beer.html
{% extends "base.html" %}

{% block title %}Add a Beer{% endblock%}

{% block content %}
<ul class="breadcrumb">
    <li><a href="/">Nick's Apartment</a> <span class="divider">/</span></li>
    <li><a href="{% url 'brewhouse-display' %}">Brewhouse</a> <span class="divider">/</span></li>
    <li class="active">New Beer</li>
</ul>

<h2>Add a beer</h2>
<form class="form-horizontal" action='.' method='POST'>
    {% if form.errors %}
    <p>Your data has errors!</p>
    <p>{{ form.errors }}</p>
    {% endif %}
    
    <div class="control-group">

    <form method="post" action="{% url 'beer-new' %}">
    {% csrf_token %}
    <label class="control-label" for="id_name">Name:</label>
    <div class="controls">
        <input id="id_name" type="text" name="name" maxlength="100" />
    </div>
    
    
    <label class="control-label" for="id_style">Style:</label>
    <div class="controls">
        <input id="id_style" type="text" name="style" maxlength="100" />
    </div>
    
    <label class="control-label" for="id_recipe_url">Recipe url:</label>
    <div class="controls">
        <input id="id_recipe_url" type="text" name="recipe_url" maxlength="1024" />
    </div>
    
    <label class="control-label" for="id_brew_date">Brew date:</label>
    <div class="controls">
        <input type="text" name="brew_date" value="2013-01-27" id="id_brew_date" />
            
    </div>

    </div>
    
    <div class="control-group">
        <div class="controls">
            <input type="submit" class="btn btn-primary" value="Add Beer" />
        </div>
    </div>


    </div>
</form>
{% endblock %}

brewhouse/templates/brewhouse/new_reservation.html
{% extends "base.html" %}

{% block title %}New Reservation{% endblock %}

{% block content %}
<ul class="breadcrumb">
    <li><a href="/">Nick's Apartment</a> <span class="divider">/</span></li>
    <li><a href="{% url 'brewhouse-display' %}">Brewhouse</a> <span class="divider">/</span></li>
    <li><a href="{% url 'beer-show' beer.id %}">{{ beer.name }}</a><span class="divider">/</span></li>
    <li class="active">Reserve</li>
</ul>

<h2>Reserve a Growler of {{ beer.name }}</h2>

<h3>By clicking the button you realize that:</h3>
<ul>
    <li>All reservations are pending approval. This allows Nick to make sure everyone gets a chance to try stuff.</li>
    <li>All beer comes in 1/2 gallon growlers. If you would not like to commit to that much, free samples are available.</li>
    <li>Reservations may be subject to a growler rental fee.</li>
</ul>
<form method="POST" action="">
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" name="doit" value="Yeah, ok, fine. Let's do this!" />
</form>
{% endblock %}

brewhouse/templates/brewhouse/reservations.html
{% extends "base.html" %}

{% block title %}Beer Reservations{% endblock %}

{% block content %}
{% if reservations %}
<h1>Your Beer Reservations</h1>
<table class="table">
    <thead>
        <tr>
            <th>Beer</th>
            <th>Approved?</th>
            <th>Fulfilled?</th>
            <th>Remove</th>
        </tr>
    </thead>
    <tbody>
        {% for r in reservations %}
        <tr>
            <td><a href="{% url 'beer-show' r.beer.id%}">{{ r.beer }}</a></td>
            <td>{{ r.approved|yesno|capfirst }}</td>
            <td>{{ r.fulfilled|yesno|capfirst }}</td>
            <td>
                <a href="{% url 'brewhouse.views.delete_reservation' r.id %}" onclick='return confirm("Are you sure you want to delete your reservation for {{r.beer.name}}?");'>
                    Remove reservation
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
    <h1>You have no beer reserved!</h1>
    <p>
        <a href="{% url 'brewhouse-display' %}">Go back to the brewhouse page</a>
    </p>
{% endif %}
{% endblock %}

brewhouse/templates/brewhouse/view_beer.html
{% extends "base.html" %}

{% block title %}Beer - {{ beer.name }}{% endblock %}

{% block content %}
<ul class="breadcrumb">
    <li><a href="/">Nick's Apartment</a> <span class="divider">/</span></li>
    <li><a href="{% url 'brewhouse-display' %}">Brewhouse</a> <span class="divider">/</span></li>
    <li class="active">{{ beer.name }}</li>
</ul>

<div class="page-header">
    <h1>{{ beer.name }}</h1>
</div>


<ul class="nav nav-pills nav-stacked">
    {% if can_reserve %}
    <li><a href="{% url 'brewhouse.views.new_reservation' beer.id %}">Reserve a growler of this beer</a></li>
    {% endif %}
    {% if user.is_staff %}
        <li><a href="{% url 'admin:brewhouse_beer_change' beer.id %}">Edit this beer in admin</a></li>
    
        {% if not beer_gone %}
            <li><a href="{% url 'brewhouse.views.beer_gone' beer.id %}" onclick="return confirm('Are you sure you want to mark this beer as gone?');">Mark this beer as gone</a></li>
        {% endif %}
    {% endif %}
</ul>


<h2>Stats</h2>
<ul>
    <li>Style: {{ beer.style|default:"Unknown" }}</li>
    <li>
        Recipe: 
        {% if beer.recipe_url %}
            <a href="{{ beer.recipe_url }}">{{ beer.recipe_url }}</a>
        {% else %}
        Unknown
        {% endif %}

    </li>
</ul>

{% if events %}
<h2>Activity</h2>
<ul>
{% for event in events %}
    <li>
        {{ event.resolve_etype }} on {{ event.date }}
    </li>
{% endfor %}
</ul>
{% endif %}

{% if future_events %}
<h2>Planned Activity</h2>
<ul>
{% for event in future_events %}
    <li>
        {{ event.resolve_etype }} on {{ event.date }}
        {% if user.is_staff %}
            (<a href="{% url 'event-complete' event.id %}" onclick="return confirm('Are you sure you want to set this event as done today?');">Did this today</a>)
        {% endif %}
    </li>
{% endfor %}
</ul>
{% endif %}

{% endblock %}